repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.11.1
    hooks:
      - id: pylint
