# To create this environment use the following command:
# conda env create -p ./env --file requirements/environment.yml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - -r requirements_dev.txt
    - -e ./..