name: tox-pytest

on: [pull_request]

jobs:

  python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox pytest
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py

  gym:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gym: ["0.21", "0.22", "0.24", "0.25", "0.26"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install tox and any other packages
        run: pip install tox pytest
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        # Note: gym also need to be set as dep in tox.ini for the force arg to work
        run: tox -e py --force-dep gym==${{ matrix.gym }}
  sb3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install tox and any other packages
        run: pip install pytest tox
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        # Note: gym also need to be set as dep in tox.ini for the force arg to work
        run: tox -e sb3
  exp-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install tox and any other packages
        run: pip install pytest tox
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        # Note: gym also need to be set as dep in tox.ini for the force arg to work
        run: tox -e exp